#
#  Author: Hari Sekhon
#  Date: 2014-11-29 01:02:47 +0000 (Sat, 29 Nov 2014)
#
#  vim:ts=4:sts=4:sw=4:et

language: perl
perl:
  - "5.20"
  - "5.8"

install:
  # causes: No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.
  - cpanm --installdeps --notest . ; :
  - make

script:
  #- PERL5OPT=-MDevel::Cover=-coverage,statement,branch,condition,path,subroutine prove -lrsv t 
  - make test

after_success:
  - cover -report coveralls
