#
#  Author: Hari Sekhon
#  Date: 2020-02-04 21:40:04 +0000 (Tue, 04 Feb 2020)
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/harisekhon/lib
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
#  https://www.linkedin.com/in/harisekhon
#

name: CI Ubuntu

env:
  DEBUG: 1

on:
  push:
    branches:
      - master
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 10 30 * *'

jobs:
  build:
    #name: build
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-16.04]

    steps:
    - uses: actions/checkout@v2
# ============================================================================
# https://github.com/actions/cache
# ============================================================================
# Perl
#		- uses: actions/cache@v1
#			with:
#				path: ~/.cpanm
#				key: ${{ runner.os }}-cpanm-${{ hashFiles('**/cpan-requirements.txt') }}
#				restore-keys: |
#					${{ runner.os }}-cpanm-
# ============================================================================
    - name: build & test
      run: make build test
